name: Go
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go build -v .
          pwd
          ls -h

      - name: copy-file-to-docker
        run: |
          cp ./https_jump ./docker/https_jump

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          workdir: ./docker

      - name: apply app server
        uses: appleboy/ssh-action@master
        env:
          IMAGE: ${{ secrets.DOCKER_IMAGE_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop http_jump
            docker rm http_jump
            docker rmi registry.cn-qingdao.aliyuncs.com/lizo/http-jump:latest
            docker run -d --name http_jump -p 80:80 registry.cn-qingdao.aliyuncs.com/lizo/http-jump:latest